make title, message optional.
dkcas11/CRNotifications pull request #28
Opened 2020-03-24 11:08 UTC by MoElnaggar14

add UIStackView that contain titleLabel, messageLabel to handle nil or empty title, message

2020-05-08 10:30 UTC, MoElnaggar14 commented
@dkcas11 please, can you check this PR?

2020-05-13 13:27 UTC, dkcas11 requested changes

2020-05-13 13:27 UTC, dkcas11 commented on CRNotifications/Classes/CRNotification.swift
> +        guard let onClickDelegate = onClickDelegate else {
Redundant.

2020-05-13 13:27 UTC, dkcas11 commented on CRNotifications/Classes/CRNotification.swift
> +        label.numberOfLines = 0
The purpose of notifications is to inform of lightweight information. If your text cannot fit within 2 lines you are doing something wrong and should use another approach to communicate your information to your user, like an alert.

2020-05-13 13:27 UTC, dkcas11 commented on CRNotifications/Classes/CRNotifications.swift
> +    func onNotificationTap()
Whats the reason for removing this entirely?

2020-05-13 13:27 UTC, dkcas11 commented on CRNotifications/Classes/CRNotification.swift
> +    public var onClickDelegate: CRNotificationDelegate?
Why is the delegate property renamed? There is no point in limiting the delegate property to such a narrow purpose. When you need other delegate methods you will need new specific protocols. It just polutes the codebase.

2020-05-13 13:32 UTC, dkcas11 commented
There is simply too big of a change in the API to consider this PR at its current state. Most of the stuff has recently been added by request of other users so this will be a breaking change in many ways.
It seems like this serves a very specific use case rather than appealing to a broader audience.
In regards to the amount of displayed text this has already been discussed a few times, such as here: https://github.com/dkcas11/CRNotifications/issues/6
Im sorry, but i think its best to fork the repo and adjust the implementation for your needs and embed the framework from there :-)

2024-07-10 16:53 UTC, closed without merging